# Generated by Django 4.0 on 2022-01-15 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sregistered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('dname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('phno', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demowebsite.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestersem', to='demowebsite.sregistered')),
                ('s_sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestersid', to='demowebsite.sregistered')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmentsid', to='demowebsite.sregistered')),
                ('deptname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmentname', to='demowebsite.sregistered')),
            ],
        ),
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=50)),
                ('cname', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demowebsite.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('s_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentemail', to='demowebsite.sregistered')),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentname', to='demowebsite.sregistered')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentid', to='demowebsite.sregistered')),
            ],
        ),
    ]
