# Generated by Django 4.0 on 2022-01-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demowebsite', '0002_remove_sregistered_user_id_alter_sregistered_phno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellor',
            name='user_id',
        ),
    ]
