# Generated by Django 4.0 on 2022-01-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demowebsite', '0003_remove_counsellor_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='d_sid',
            new_name='sid',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='s_sem',
            new_name='sem',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='s_sid',
            new_name='sid',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='counsellor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sregistered',
            name='id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='cid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sregistered',
            name='sid',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
