# Generated by Django 4.0 on 2022-01-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demowebsite', '0004_rename_d_sid_department_sid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='id',
            new_name='aid',
        ),
    ]
