# Generated by Django 4.0 on 2022-01-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demowebsite', '0005_rename_id_appointment_aid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='sid',
            new_name='d_sid',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='sem',
            new_name='s_sem',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='sid',
            new_name='s_sid',
        ),
    ]
