# Generated by Django 4.0 on 2022-01-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demowebsite', '0006_rename_sid_department_d_sid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sregistered',
            name='sid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
