# Generated by Django 4.0 on 2022-01-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demowebsite', '0007_alter_sregistered_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='aid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sregistered',
            name='sid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
