# Generated by Django 4.0 on 2022-01-16 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demowebsite', '0008_alter_appointment_aid_alter_sregistered_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='aid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='studentid', serialize=False, to='demowebsite.sregistered'),
        ),
    ]
