# Generated by Django 4.0 on 2022-01-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demowebsite', '0009_alter_appointment_aid_alter_appointment_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='aid',
        ),
    ]
