# Generated by Django 4.0 on 2022-01-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demowebsite', '0010_remove_appointment_aid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='mssg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_no',
            field=models.CharField(default='DEFAULT VALUE', max_length=10),
        ),
    ]
