# Generated by Django 4.0 on 2022-01-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demowebsite', '0011_appointment_mssg_appointment_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='phone_no',
            new_name='Number',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='mssg',
            new_name='mssgs',
        ),
    ]
