# Generated by Django 4.0 on 2022-01-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demowebsite', '0012_rename_phone_no_appointment_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Number',
            new_name='contact',
        ),
    ]
